global:
  checkNewVersion: false
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    constraints: "Label(`traefik.constraint-label`, `traefik-public`)"
  file:
    directory: /etc/traefik/dynamic
    watch: true
entryPoints:
  http:
    address: :80
    transport:
      respondingTimeouts:
        readTimeout: 0
  https:
    address: :443
    transport:
      respondingTimeouts:
        readTimeout: 0

certificatesResolvers:
  le:
    acme:
      email: email@domain.com 
      storage: /certificates/acme.json
      # Production
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      # Staging
      #caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
api:
  dashboard: true
log:
  level: ERROR
  format: common
  filePath: /var/log/traefik/traefik.log
accesslog:
  format: common
  filePath: /var/log/traefik/traefik-access.log
  bufferingSize: 100
